Models/ErrorViewModel.cs
namespace LearnMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace LearnMVC.Models
{
    public class Product
    {
        public int ProductId { get; set; }
        [Display(Name = "Product Name")]
        public string Name { get; set; }

        [Display(Name = "Product Quantitiy")]
        public int Quantity { get; set; }

        [Display(Name = "Product Price")] 
        public decimal Price { get; set; }

        [Display(Name = "Available")] 
        public bool InStock { get; set; }

        [Display(Name = "Publish")] 
        public bool InPublish { get; set; }
    }
}

Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace LearnMVC.Models
{
    public class User
    {
        //Globally unique ID
        // we need to use [Key] to knowing it's an Primary Key
        [Key]
        public Guid UserId { get; set; }
        public string? UserName { get; set; }

        [DataType(DataType.Password)]
        [MaxLength(50)]
        [Required]
        public string? Password { get; set; }

        public bool IsActive { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

Controllers/HomeController.cs
using LearnMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LearnMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductsController.cs
using LearnMVC.Data;
using LearnMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace LearnMVC.Controllers
{
    public class ProductsController : Controller
    {
        public AppDbContext context { get; }
        public ProductsController(AppDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            return View(context.products.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product model)
        {
            context.products.Add(model);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult ChangeStatus(int id)
        {
            var product = context.products.Find(id);
            product.InPublish = !product.InPublish;
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/UsersController.cs
using LearnMVC.Data;
using LearnMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace LearnMVC.Controllers
{
    public class UsersController : Controller
    {
        private readonly AppDbContext context;
        public UsersController(AppDbContext context)
        {
            this.context = context;
        }


        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(User usr)
        {
            context.Users.Add(usr);
            context.SaveChanges();
            return RedirectToAction(nameof(Login));
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(User user)
        {
            var checkUser = context.Users.Where(u => u.UserName == user.UserName && u.Password == user.Password);

            if(checkUser.Any()) return RedirectToAction(nameof(Index));

            ViewBag.Error = "Invalid username or password";
            return View(user);
        }

        public IActionResult Index()
        {
            return View(context.Users.ToList());
        }

        public IActionResult ChangeActive(Guid id)
        {
            var user = context.Users.Find(id);
            user.IsActive = !user.IsActive;
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Products/Create.cshtml
@model LearnMVC.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create Products</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Products" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="InStock" /> @Html.DisplayNameFor(model => model.InStock)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="InPublish" /> @Html.DisplayNameFor(model => model.InPublish)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Products/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@if(Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <td>@Html.DisplayNameFor(model => model.Name)</td>
                <td>@Html.DisplayNameFor(model => model.Price)</td>
                <td>@Html.DisplayNameFor(model => model.Quantity)</td>
                <td>@Html.DisplayNameFor(model => model.InPublish)</td>
            </tr>
        </thead>

        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Price</td>
                    <td>@item.Quantity</td>
                    <td>
                        @if (item.InPublish == true)
                        {
                            <a class="btn btn-@(item.InPublish ? "Success" : "danger")"
                                asp-controller="Products"
                                asp-action="ChangeStatus"
                                asp-route-id = "@item.ProductId">
                                @(item.InPublish == true ? "Un-Publish" : "Publish")
                            </a>
                        }else
                        {
                            <a class="btn btn-@(item.InPublish ? "Success" : "danger")"
                               asp-controller="Products"
                               asp-action="ChangeStatus"
                               asp-route-id="@item.ProductId">
                               @(item.InPublish == true ? "Un-Publish" : "Publish")
                           </a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info">No Data found</div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LearnMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LearnMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LearnMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LearnMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Users/Index.cshtml
@model IEnumerable<LearnMVC.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h1>Display Users</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @item.UserId
                </td>
                <td>
                    @item.UserName
                </td>
                <td>
                    @item.Password
                </td>
                <td>
                    @item.CreatedAt
                </td>
                <td>
                    <a class="btn btn-@(item.IsActive == true ? "danger" : "success")"
                        asp-controller="Users"
                        asp-action="ChangeActive"
                        asp-route-id="@item.UserId"
                        >
                        @(item.IsActive == true ? "Enable" : "Disable")
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Users/Login.cshtml
@model User

@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<div class="text-danger">@ViewBag.Error</div>
<form asp-controller="Users" asp-action="Login">
    <div class="my-3">
        <label asp-for="UserName"></label>
        <input asp-for="UserName" class="form-control" />
    </div>
    <div class="my-3">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" />
    </div>

    <button type="submit" class="btn btn-outline-primary">Login</button>
</form>

Views/Users/Register.cshtml
@model User

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<form asp-controller="Users" asp-action="Register">
    <div class="my-3">
        <label asp-for="UserName"></label>
        <input asp-for="UserName" class="form-control" />
    </div>
    <div class="my-3">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" />
    </div>

    <div class="my-3">
        <label asp-for="CreatedAt"></label>
        <input asp-for="CreatedAt" class="form-control" />
    </div>

    <button type="submit" class="btn btn-outline-primary">Register</button>
</form>